export const CartActionTypes = {
    TOGGLE_CART_HIDDEN:'TOGGLE_CART_HIDDEN',
    ADD_ITEM:'ADD_ITEM',
    CLEAR_ITEM_FROM_CART:'CLEAR_ITEM_FROM_CART',
    DECREASE_QUANTITY_ITEM:'DECREASE_QUANTITY_ITEM',
}